Adicionando máscara em campos com número
ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-1-e2-proj-int-t3-church-admin pull request #26
Opened 2022-05-29 16:16 UTC by kaiohenrikk

2022-05-30 21:08 UTC, Jhonata-Jackson requested changes
Esqueceu de fazer o upload da alteração no package.json que inclui o react-input-mask no projeto. Da maneiro que está eu baixo o projeto do yarn, mas quando vou rodar ele quebra pq não sabe oq é react-input-mask. Está quebrado esse pr

2022-06-01 00:37 UTC, MerianeRDias approved these changes

2022-06-01 00:37 UTC, abmagna approved these changes

2022-06-01 00:40 UTC, ThiagoRoberto85 approved these changes

2022-06-01 00:54 UTC, kaiohenrikk commented
> Esqueceu de fazer o upload da alteração no package.json que inclui o react-input-mask no projeto. Da maneiro que está quando vou rodar ele quebra pq não sabe oq é react-input-mask mesmo dps de dar yarn na pasta. Está quebrado esse pr
Resolvido.

2022-06-06 23:50 UTC, merged